version: '3.6'

services:
  api:
    build:
      context: ./backend
    ports:
      - 8000:8000
    env_file:
      - .env

  ui:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    env_file:
      - .env
