on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build python app and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: florzattera/craft-challenge-python-app:latest
        context: second_exercise/backend

    - name: install and build website
      run: |
        cd third_exercise/my-app
        npm install
        npm run build

    - name: deploy website
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build      

    #- name: deploy python app
    #  uses: steebchen/kubectl@v2.0.0
    #  with: # defaults to latest kubectl binary version
    #    config: ${{ secrets.KUBE_CONFIG_DATA }}
    #    command: set image --record florzattera/craft-challenge-python-app container=${{ github.repository }}:${{ github.sha }}
    #- name: verify deployment
    #  uses: steebchen/kubectl@v2.0.0
    #  with:
    #    config: ${{ secrets.KUBE_CONFIG_DATA }}
    #    version: v1.21.0 # specify kubectl binary version explicitly
    #    command: rollout status florzattera/craft-challenge
